// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAsZmfo9Sas7u0467w6mxZbp7PC6xpBU',
    appId: '1:502315548379:web:bcdd154c8e20de87c516fe',
    messagingSenderId: '502315548379',
    projectId: 'fluttersignin-35434',
    authDomain: 'fluttersignin-35434.firebaseapp.com',
    storageBucket: 'fluttersignin-35434.appspot.com',
    measurementId: 'G-JKS15TG9YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtw2DnUBh7mzNN3PEi5Rondrye5FPBsbs',
    appId: '1:502315548379:android:047024d3cc0e7c3dc516fe',
    messagingSenderId: '502315548379',
    projectId: 'fluttersignin-35434',
    storageBucket: 'fluttersignin-35434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrta77ciDWbrUsdNwua2Mqb8uRtBA4vY',
    appId: '1:502315548379:ios:d28dce4852a51eacc516fe',
    messagingSenderId: '502315548379',
    projectId: 'fluttersignin-35434',
    storageBucket: 'fluttersignin-35434.appspot.com',
    iosClientId: '502315548379-9fu0kh8b9vh3uqjr0unqv96q41cjhs2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.truth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxAsZmfo9Sas7u0467w6mxZbp7PC6xpBU',
    appId: '1:502315548379:web:bcdd154c8e20de87c516fe',
    messagingSenderId: '502315548379',
    projectId: 'fluttersignin-35434',
    authDomain: 'fluttersignin-35434.firebaseapp.com',
    storageBucket: 'fluttersignin-35434.appspot.com',
    measurementId: 'G-JKS15TG9YV',
  );
}
